#!/bin/sh

echo "Create snapshot..."
mv "/usr/share/X11/xkb/symbols/ir" "/usr/share/X11/xkb/ir.bk"
mv "/usr/share/X11/xkb/rules/base.xml" "/usr/share/X11/xkb/base.xml.bk"
mv "/usr/share/X11/xkb/rules/evdev.xml" "/usr/share/X11/xkb/evdev.xml.bk"
mv "/usr/share/X11/xkb/rules/base.extras.xml" "/usr/share/X11/xkb/base.extras.bk"
mv "/usr/share/X11/xkb/rules/evdev.extras.xml" "/usr/share/X11/xkb/evdev.extras.bk"
mv "/usr/share/X11/xkb/rules/base.lst" "/usr/share/X11/xkb/base.lst.bk"
mv "/usr/share/X11/xkb/rules/evdev.lst" "/usr/share/X11/xkb/evdev.lst.bk"

echo "Installing..."
cp "./src/ir" "/usr/share/X11/xkb/symbols/ir"
cp "./src/base.xml" "/usr/share/X11/xkb/rules/base.xml"
cp "./src/evdev.xml" "/usr/share/X11/xkb/rules/evdev.xml"
cp "./src/base.extras.xml" "/usr/share/X11/xkb/rules/base.extras.xml" 
cp "./src/evdev.extras.xml" "/usr/share/X11/xkb/rules/evdev.extras.xml" 
cp "./src/base.lst" "/usr/share/X11/xkb/rules/base.lst" 
cp "./src/evdev.lst" "/usr/share/X11/xkb/rules/evdev.lst" 
echo "Done"
